
spring:
    main:
        allow-circular-references: true

    datasource:
        url: jdbc:h2:mem:onlinestore

    data:
        jpa:
            repositories:
                bootstrap-mode: default
                
    h2:
        console:
            enabled: false

    artemis:
        user: artemis
        password: simetraehcapa
        broker-url: tcp://localhost:61616

server:
  port: 80

store:
    app:
        jwtSecret: jwtSecret
        jwtExpirationMs: 86400000