
spring:
    datasource:
        url: jdbc:h2:mem:onlinestore

    data:
        jpa:
            repositories:
                bootstrap-mode: default

    h2:
        console:
            enabled: true

#    autoconfigure:
#        exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration

    artemis:
        user: artemis
        password: simetraehcapa
        host: artemis